# Portable binary -> C array generator (no xxd, works under clang-cl on Windows).
#
# Invoked at build time via `cmake -P cmake/embed_font.cmake` with:
#   -DIN_TTF=<input .ttf>        the binary to embed
#   -DOUT_CPP=<output .cpp>      the translation unit to write
#   -DSYM=<symbol>              base C symbol name (defines <SYM>[] and <SYM>Len)
#   -DHEADER_NAME=<header>       declarations header to #include (extern decls)
#
# Emits a single .cpp defining the byte array + its length. The matching extern
# declarations live in HEADER_NAME so the symbols can be referenced from any TU
# without an ODR hazard.

file(READ "${IN_TTF}" hex HEX)
string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${hex}")

file(WRITE "${OUT_CPP}"
"// AUTO-GENERATED by cmake/embed_font.cmake from ${IN_TTF}. Do not edit.\n"
"#include \"${HEADER_NAME}\"\n"
"extern const unsigned char ${SYM}[] = { ${bytes} };\n"
"extern const unsigned int  ${SYM}Len = sizeof(${SYM});\n")
