# Build-time wrapper around the vendored binary_to_compressed_c tool.
#
# Invoked at build time via `cmake -P cmake/run_font_compressor.cmake` with:
#   -DTOOL=<compressor exe>     $<TARGET_FILE:nothofagus_font_compressor>
#   -DIN_TTF=<input .ttf>        the binary to embed
#   -DOUT_CPP=<output .cpp>      the translation unit to write
#   -DSYM=<symbol>              base symbol; tool emits <SYM>_compressed_data[]
#                                and <SYM>_compressed_size
#   -DHEADER_NAME=<header>       declarations header to #include (extern decls)
#
# The tool writes the C array to stdout. We capture it and PREPEND the
# `#include "<header>"`. That header declares the symbols `extern`, which gives
# the tool's plain `const` definitions external linkage (namespace-scope const
# is internal-linkage by default in C++) so other TUs can reference them.

execute_process(
    COMMAND "${TOOL}" -u8 -nostatic "${IN_TTF}" "${SYM}"
    OUTPUT_VARIABLE _src
    RESULT_VARIABLE _rc)

if(NOT _rc EQUAL 0)
    message(FATAL_ERROR "binary_to_compressed_c failed (${_rc}) for ${IN_TTF}")
endif()

file(WRITE "${OUT_CPP}"
"// AUTO-GENERATED by cmake/run_font_compressor.cmake from ${IN_TTF}. Do not edit.\n"
"#include \"${HEADER_NAME}\"\n"
"${_src}")
